import './style.css';

type Formation = 'line' | 'column' | 'arrow' | 'circle' | 'pincer';
type FireMode = 'focus' | 'atwill' | 'hold';
type Side = 'player' | 'enemy';
type Vec = { x: number; y: number };
type Body = { kind: 'planet' | 'asteroids'; pos: Vec; radius: number; base?: Side; stock?: number; hue: number };
type Ship = { id: number; side: Side; role: 'battleship' | 'supply' | 'captain'; pos: Vec; vel: Vec; hp: number; maxHp: number; attack: number; defense: number; speed: number; sight: number; moral: number; supplies: number; range: number; cooldown: number; target?: Vec };
type Config = { ships: number; planets: number; asteroids: number; speed: number };

const canvas = document.querySelector<HTMLCanvasElement>('#game')!;
const ctx = canvas.getContext('2d')!;
const status = document.querySelector('#status')!;
const readout = document.querySelector('#order-readout')!;
const formationControls = document.querySelector('#formation-controls')!;
const fireControls = document.querySelector('#fire-controls')!;
const tightness = document.querySelector<HTMLInputElement>('#tightness')!;
const tightnessValue = document.querySelector('#tightness-value')!;
let dpr = 1, width = 1, height = 1, time = 0;
let config: Config = { ships: 10, planets: 5, asteroids: 3, speed: 1 };
let formation: Formation = 'arrow', fireMode: FireMode = 'atwill', command: Vec | null = null, pointer: Vec | null = null;
let bodies: Body[] = [], ships: Ship[] = [], flashes: { from: Vec; to: Vec; life: number; side: Side }[] = [];
let captainFavorite: Formation = 'line', winner: Side | null = null;
const formations: Formation[] = ['line', 'column', 'arrow', 'circle', 'pincer'];
const fireModes: FireMode[] = ['focus', 'atwill', 'hold'];
const colors = { player: '#5de5ff', enemy: '#ff6d91' };
const rnd = (a: number, b: number) => a + Math.random() * (b - a);
const dist = (a: Vec, b: Vec) => Math.hypot(a.x - b.x, a.y - b.y);
const norm = (v: Vec) => { const l = Math.hypot(v.x, v.y) || 1; return { x: v.x / l, y: v.y / l }; };
const clamp = (n: number, a: number, b: number) => Math.max(a, Math.min(b, n));

function formationSvg(f: Formation) { const p = (x:number,y:number) => `<circle cx="${x}" cy="${y}" r="2" fill="currentColor"/>`; let dots = ''; if(f === 'line') dots=[7,13,19,25].map(x=>p(x,14)).join(''); if(f === 'column') dots=[6,12,18,24].map(y=>p(16,y)).join(''); if(f === 'arrow') dots=[[16,7],[11,14],[21,14],[7,21],[25,21]].map(([x,y])=>p(x,y)).join(''); if(f === 'circle') dots=[[16,6],[25,11],[25,19],[16,24],[7,19],[7,11]].map(([x,y])=>p(x,y)).join(''); if(f === 'pincer') dots=[[7,7],[12,12],[7,21],[12,17],[25,7],[20,12],[25,21],[20,17]].map(([x,y])=>p(x,y)).join(''); return `<svg viewBox="0 0 32 30">${dots}</svg>`; }
function fireSvg(mode: FireMode) { if (mode === 'hold') return '<svg viewBox="0 0 32 30"><path d="M7 19h17l-3-4H11zM12 14l2-5h4l2 5" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="22" cy="9" r="7" fill="#081724" stroke="#ff7292" stroke-width="2"/><path d="M17 4l10 10" stroke="#ff7292" stroke-width="2"/></svg>'; const spread = mode === 'focus' ? 'M14 7h4M14 12h4M14 17h4' : 'M11 7h4M15 12h4M19 17h4'; return `<svg viewBox="0 0 32 30"><path d="M6 22h17l-3-5H10zM12 17l2-5h4l2 5" fill="none" stroke="currentColor" stroke-width="2"/><path d="${spread}" stroke="#80efff" stroke-width="2"/></svg>`; }
function setupControls() {
  formations.forEach(f => { const b = document.createElement('button'); b.ariaLabel = `${f} formation`; b.dataset.value = f; b.innerHTML = formationSvg(f); b.onclick = () => { formation = f; command = null; selectActive(formationControls, f); readout.textContent = `${f.toUpperCase()} SELECTED — TAP MAP TO SET FLEET POSITION`; }; formationControls.append(b); });
  fireModes.forEach(m => { const b = document.createElement('button'); b.ariaLabel = m; b.dataset.value = m; b.innerHTML = fireSvg(m); b.onclick = () => { fireMode = m; selectActive(fireControls, m); readout.textContent = m === 'hold' ? 'WEAPONS HOLD' : m === 'focus' ? 'FOCUS FIRE — TAP AN ENEMY TO DESIGNATE' : 'WEAPONS FREE — ENGAGING HOSTILES IN RANGE'; }; fireControls.append(b); });
  selectActive(formationControls, formation); selectActive(fireControls, fireMode);
  tightness.oninput = () => { tightnessValue.textContent = `${tightness.value}%`; };
  document.querySelector('#debug-toggle')!.addEventListener('click', () => document.body.classList.toggle('debug-open'));
  document.querySelector('#reset-game')!.addEventListener('click', reset);
  for (const id of ['ship-count', 'planet-count', 'asteroid-count', 'game-speed']) { const el = document.querySelector<HTMLInputElement>('#' + id)!; const out = el.parentElement!.querySelector('output')!; const update = () => { out.textContent = id === 'game-speed' ? `${el.value}×` : el.value; }; update(); el.oninput = update; }
}
function selectActive(root: Element, value: string) { root.querySelectorAll('button').forEach(b => b.classList.toggle('active', (b as HTMLElement).dataset.value === value)); }
function getConfig() { config = { ships: +document.querySelector<HTMLInputElement>('#ship-count')!.value, planets: +document.querySelector<HTMLInputElement>('#planet-count')!.value, asteroids: +document.querySelector<HTMLInputElement>('#asteroid-count')!.value, speed: +document.querySelector<HTMLInputElement>('#game-speed')!.value }; }
function resize() { dpr = Math.min(devicePixelRatio, 2); width = innerWidth; height = innerHeight; canvas.width = width*dpr; canvas.height = height*dpr; ctx.setTransform(dpr,0,0,dpr,0,0); }
function spawnShip(side: Side, role: Ship['role'], pos: Vec, id: number): Ship { const battle = role === 'battleship'; return { id, side, role, pos: { ...pos }, vel: { x: rnd(-12,12), y:rnd(-12,12) }, hp: battle ? 100 : role === 'captain' ? 150 : 80, maxHp: battle ? 100 : role === 'captain' ? 150 : 80, attack: battle ? 14 : role === 'captain' ? 8 : 0, defense: battle ? 3 : 5, speed: battle ? 56 : 45, sight: 260, moral: 70, supplies: battle ? 10 : 0, range: battle ? 135 : 80, cooldown: rnd(0,.8) }; }
function reset() { getConfig(); winner = null; command = null; flashes=[]; ships=[]; bodies=[]; const margin = 100; const playerBase = { x: rnd(margin, width*.28), y:rnd(margin,height-margin) }; const enemyBase = {x:rnd(width*.72,width-margin),y:rnd(margin,height-margin)}; bodies.push({kind:'planet',pos:playerBase,radius:37,base:'player',stock:0,hue:195},{kind:'planet',pos:enemyBase,radius:37,base:'enemy',stock:0,hue:350});
  for(let i=2;i<config.planets;i++) bodies.push({kind:'planet',pos:{x:rnd(120,width-120),y:rnd(100,height-100)},radius:rnd(20,34),stock:0,hue:rnd(25,290)});
  for(let i=0;i<config.asteroids;i++) bodies.push({kind:'asteroids',pos:{x:rnd(100,width-100),y:rnd(80,height-80)},radius:rnd(32,58),hue:0});
  captainFavorite = formations[Math.floor(Math.random()*formations.length)]; let id=0; for (const side of ['player','enemy'] as Side[]) { const base = side === 'player' ? playerBase : enemyBase; for(let i=0;i<config.ships;i++) ships.push(spawnShip(side,'battleship',{x:base.x+rnd(-75,75),y:base.y+rnd(-75,75)},id++)); ships.push(spawnShip(side,'supply',{x:base.x+rnd(-35,35),y:base.y+rnd(-35,35)},id++)); ships.push(spawnShip(side,'captain',{x:base.x+rnd(-30,30),y:base.y+rnd(-30,30)},id++)); }
  readout.textContent = `CAPTAIN FAVORS ${captainFavorite.toUpperCase()} — SELECT A FORMATION, THEN TAP THE MAP`;
}
function slots(center: Vec, f: Formation, n: number, spacing: number) { const out: Vec[]=[]; for(let i=0;i<n;i++){ let x=0,y=0; if(f==='line'){x=(i-(n-1)/2)*spacing;} if(f==='column'){y=(i-(n-1)/2)*spacing;} if(f==='arrow'){const row=Math.floor((Math.sqrt(8*i+1)-1)/2), start=row*(row+1)/2; x=(i-start-row/2)*spacing;y=(row-2)*spacing*.7;} if(f==='circle'){const a=i/n*Math.PI*2;x=Math.cos(a)*spacing*1.8;y=Math.sin(a)*spacing*1.8;} if(f==='pincer'){const half=i<n/2?-1:1, j=i%(Math.ceil(n/2));x=half*(spacing*1.2+j*spacing*.55);y=(j-(n/4))*spacing;} out.push({x:center.x+x,y:center.y+y}); } return out; }
function damage(target: Ship, amount: number) { target.hp -= Math.max(1, amount-target.defense); target.moral=clamp(target.moral-5,0,100); }
function update(dt: number) { if(winner)return; dt*=config.speed; time+=dt; for(const b of bodies) if(b.kind==='planet') b.stock=(b.stock||0)+dt*1.1; const player = ships.filter(s=>s.side==='player'); const enemy = ships.filter(s=>s.side==='enemy');
  for(const fleet of [player,enemy]) { const side=fleet[0]?.side; if(!side) continue; const playerFleet=side==='player'; const center=playerFleet ? (command || bodies.find(b=>b.base==='player')!.pos) : bodies.find(b=>b.base==='player')!.pos; const f=playerFleet?formation:'arrow'; const cohesion=(+tightness.value/100); const battle=fleet.filter(s=>s.role==='battleship'); const targets=slots(center,f,battle.length,clamp(80-(cohesion*50),25,70)); battle.forEach((s,i)=>s.target=targets[i]); fleet.filter(s=>s.role!=='battleship').forEach((s,i)=>s.target={x:center.x+(i?20:-20),y:center.y+60}); }
  for(const s of ships) { s.cooldown-=dt; if(s.role==='supply'){ for(const ally of ships.filter(a=>a.side===s.side&&a.role==='battleship'&&dist(a.pos,s.pos)<70&&a.supplies<10)){const give=Math.min(dt*3,s.supplies,10-ally.supplies); s.supplies-=give;ally.supplies+=give;} } for(const p of bodies.filter(b=>b.kind==='planet'&&dist(s.pos,b.pos)<b.radius+45)){ if(p.base===s.side || !p.base){const take=Math.min(dt*2,p.stock||0, 10-s.supplies);s.supplies+=take;p.stock=(p.stock||0)-take;} }
    let force={x:0,y:0}; if(s.target){const v={x:s.target.x-s.pos.x,y:s.target.y-s.pos.y}; const d=Math.hypot(v.x,v.y); force={x:v.x/(d||1)*s.speed,y:v.y/(d||1)*s.speed};} for(const other of ships){if(other===s)continue;const d=dist(s.pos,other.pos);if(d<42){const n=norm({x:s.pos.x-other.pos.x,y:s.pos.y-other.pos.y});force.x+=n.x*(42-d)*3;force.y+=n.y*(42-d)*3;}} for(const b of bodies){const d=dist(s.pos,b.pos), safe=b.radius+30;if(d<safe){const n=norm({x:s.pos.x-b.pos.x,y:s.pos.y-b.pos.y});force.x+=n.x*(safe-d)*5;force.y+=n.y*(safe-d)*5;}} s.vel.x+=(force.x-s.vel.x)*Math.min(1,dt*2.2);s.vel.y+=(force.y-s.vel.y)*Math.min(1,dt*2.2);s.pos.x=clamp(s.pos.x+s.vel.x*dt,10,width-10);s.pos.y=clamp(s.pos.y+s.vel.y*dt,10,height-10);
    const opponents=ships.filter(o=>o.side!==s.side); const near=opponents.filter(o=>dist(s.pos,o.pos)<s.range); const shouldShoot=s.role==='battleship'&&s.supplies>=1&&s.cooldown<=0&&near.length&& (s.side==='enemy'||fireMode!=='hold'); if(shouldShoot){let target=near[0]; if(s.side==='player'&&fireMode==='focus'&&pointer){target=near.sort((a,b)=>dist(a.pos,pointer!)-dist(b.pos,pointer!))[0];} const bonus=s.side==='player'&&formation===captainFavorite?1.25:1;damage(target,s.attack*bonus);s.supplies--;s.cooldown=.75;flashes.push({from:{...s.pos},to:{...target.pos},life:.12,side:s.side});}
  }
  ships=ships.filter(s=>s.hp>0); flashes=flashes.filter(f=>(f.life-=dt)>0); const pb=bodies.find(b=>b.base==='player')!, eb=bodies.find(b=>b.base==='enemy')!; for(const b of [pb,eb]){const attackers=ships.filter(s=>s.side!==b.base&&dist(s.pos,b.pos)<s.range&&s.role==='battleship'&&s.supplies>0);if(attackers.length&&Math.random()<dt*.3){b.radius-=attackers.length*.16; attackers.forEach(s=>s.supplies-=.2);}} if(pb.radius<12||eb.radius<12)winner=pb.radius<12?'enemy':'player';
}
function drawBackground(){ctx.fillStyle='#050a13';ctx.fillRect(0,0,width,height);for(let i=0;i<160;i++){const x=(i*211.3)%width,y=(i*97.1)%height;ctx.fillStyle=`rgba(180,220,255,${.12+(i%5)*.06})`;ctx.fillRect(x,y,1,1);} const g=ctx.createRadialGradient(width*.53,height*.48,30,width*.53,height*.48,Math.max(width,height)*.7);g.addColorStop(0,'#0b2637');g.addColorStop(1,'#050a13');ctx.fillStyle=g;ctx.fillRect(0,0,width,height);}
function draw(){drawBackground(); for(const b of bodies){ctx.save();ctx.translate(b.pos.x,b.pos.y);if(b.kind==='asteroids'){for(let i=0;i<15;i++){const a=i*.9, r=b.radius*(.3+(i%3)*.22);ctx.fillStyle='#78818b';ctx.beginPath();ctx.arc(Math.cos(a)*r,Math.sin(a)*r,3+i%4,0,7);ctx.fill();}}else{const glow=ctx.createRadialGradient(-b.radius*.3,-b.radius*.3,2,0,0,b.radius*1.7);glow.addColorStop(0,`hsla(${b.hue},80%,80%,.95)`);glow.addColorStop(.45,`hsla(${b.hue},75%,42%,.9)`);glow.addColorStop(1,`hsla(${b.hue},75%,30%,0)`);ctx.fillStyle=glow;ctx.beginPath();ctx.arc(0,0,b.radius*1.7,0,7);ctx.fill();ctx.fillStyle=`hsl(${b.hue},65%,42%)`;ctx.beginPath();ctx.arc(0,0,b.radius,0,7);ctx.fill();if(b.base){ctx.strokeStyle=colors[b.base];ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,b.radius+6,0,7);ctx.stroke();}}ctx.restore();}
  if(pointer&&formation){const sl=slots(command||pointer,formation,config.ships,clamp(80-(+tightness.value/100*50),25,70));ctx.strokeStyle='#62e8ff66';ctx.setLineDash([5,5]);ctx.beginPath();ctx.arc((command||pointer).x,(command||pointer).y,10,0,7);ctx.stroke();ctx.setLineDash([]);sl.forEach(p=>{ctx.fillStyle='#62e8ff77';ctx.beginPath();ctx.arc(p.x,p.y,5,0,7);ctx.fill();});}
  for(const f of flashes){ctx.strokeStyle=f.side==='player'?'#8df6ff':'#ff86a3';ctx.globalAlpha=f.life/.12;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(f.from.x,f.from.y);ctx.lineTo(f.to.x,f.to.y);ctx.stroke();ctx.globalAlpha=1;}
  for(const s of ships){ctx.save();ctx.translate(s.pos.x,s.pos.y);ctx.rotate(Math.atan2(s.vel.y,s.vel.x)+Math.PI/2);ctx.fillStyle=colors[s.side];ctx.beginPath(); if(s.role==='supply'){ctx.rect(-6,-8,12,16);}else{ctx.moveTo(0,-10);ctx.lineTo(7,8);ctx.lineTo(0,5);ctx.lineTo(-7,8);ctx.closePath();}ctx.fill();ctx.restore();ctx.fillStyle='#000a';ctx.fillRect(s.pos.x-11,s.pos.y-17,22,3);ctx.fillStyle=s.side==='player'?'#69eaff':'#ff6e91';ctx.fillRect(s.pos.x-11,s.pos.y-17,22*(s.hp/s.maxHp),3); if(s.side==='player'){ctx.fillStyle='#c9efff';ctx.font='10px Rajdhani';ctx.fillText(`${Math.floor(s.supplies)}`,s.pos.x+9,s.pos.y+8);}}
  const p=ships.filter(s=>s.side==='player').length,e=ships.filter(s=>s.side==='enemy').length;status.innerHTML=`<span style="color:#5de5ff">◈ ${p} FLEET</span><br><span style="color:#ff7898">◇ ${e} HOSTILES</span>`;if(winner){ctx.fillStyle='#03101ad9';ctx.fillRect(0,0,width,height);ctx.fillStyle=winner==='player'?'#6eeeff':'#ff7797';ctx.textAlign='center';ctx.font='700 42px Barlow Condensed';ctx.fillText(winner==='player'?'ENEMY BASE DESTROYED':'COMMAND FLEET LOST',width/2,height/2);ctx.font='600 16px Rajdhani';ctx.fillText('Use the debug reset control to run another simulation',width/2,height/2+32);ctx.textAlign='left';}}
let last=performance.now();function loop(now:number){const dt=Math.min(.05,(now-last)/1000);last=now;update(dt);draw();requestAnimationFrame(loop);}function mapPoint(e:PointerEvent){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};}canvas.addEventListener('pointermove',e=>pointer=mapPoint(e));canvas.addEventListener('pointerleave',()=>pointer=null);canvas.addEventListener('pointerdown',e=>{pointer=mapPoint(e);command={...pointer};readout.textContent=`FLEET MOVING IN ${formation.toUpperCase()} FORMATION — COHESION ${tightness.value}%`;});window.addEventListener('resize',()=>{resize();reset();});setupControls();resize();reset();requestAnimationFrame(loop);
